# ============================
#   SIGNAL K – ENVIRONMENT
# ============================

# Depth Below Transducer
- resource: !secret signalk_env_depth
  headers:
    Authorization: !secret signalk_token
  scan_interval: 5
  sensor:
    - name: "SignalK Depth"
      unique_id: "signalk_depth"
      value_template: "{{ value_json.value }}"
      unit_of_measurement: "m"

# Apparent Wind Angle
- resource: !secret signalk_env_wind_angle_app
  headers:
    Authorization: !secret signalk_token
  scan_interval: 5
  sensor:
    - name: "SignalK Wind Angle Apparent"
      unique_id: "signalk_wind_angle_apparent"
      value_template: "{{ value_json.value }}"
      unit_of_measurement: "rad"

# True Wind Angle (Water)
- resource: !secret signalk_env_wind_angle_true
  headers:
    Authorization: !secret signalk_token
  scan_interval: 5
  sensor:
    - name: "SignalK Wind Angle True Water"
      unique_id: "signalk_wind_angle_true_water"
      value_template: "{{ value_json.value }}"
      unit_of_measurement: "rad"

# Apparent Wind Speed
- resource: !secret signalk_env_wind_speed_app
  headers:
    Authorization: !secret signalk_token
  scan_interval: 5
  sensor:
    - name: "SignalK Wind Speed Apparent"
      unique_id: "signalk_wind_speed_apparent"
      value_template: "{{ value_json.value }}"
      unit_of_measurement: "m/s"

# True Wind Speed
- resource: !secret signalk_env_wind_speed_true
  headers:
    Authorization: !secret signalk_token
  scan_interval: 5
  sensor:
    - name: "SignalK Wind Speed True"
      unique_id: "signalk_wind_speed_true"
      value_template: "{{ value_json.value }}"
      unit_of_measurement: "m/s"
