- id: '1780520628159'
  alias: Daily Git Export
  trigger:
    - platform: time
      at: "03:00:00"
  action:
    - service: hassio.addon_restart
      data:
        addon: 68413af6_git-exporter
  mode: single

