# Use this file to store secrets like usernames and passwords.
# Learn more at https: ""
latitude: ""
longitude: ""
elevation: ""

signalk_nav_position: ""
signalk_nav_cog_true: ""
signalk_nav_cog_mag: ""
signalk_nav_hdg_true: ""
signalk_nav_hdg_mag: ""
signalk_nav_sog: ""
signalk_nav_stw: ""

signalk_env_depth: ""
signalk_env_wind_angle_app: ""
signalk_env_wind_angle_true: ""
signalk_env_wind_speed_app: ""
signalk_env_wind_speed_true: ""

signalk_perf_vmg: ""

signalk_engine1_rpm: ""
signalk_engine1_temp: ""

signalk_token: ""
