anchorage_latitude:
  name: Anchorage Latitude
  min: -90
  max: 90
  step: 0.000001
  mode: box
  initial: 48.45037

anchorage_longitude:
  name: Anchorage Longitude
  min: -180
  max: 180
  step: 0.000001
  mode: box
  initial: -123.569192

anchorage_radius:
  name: Anchorage Radius
  min: 10
  max: 150
  step: 1
  initial: 50
